baseurl = "https://www.kofuk.org/"
title = "チラシの表の反対側"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
paginate = "10"
hasCJKLanguage = true
summaryLength = 300
enableEmoji = true

[Params]
  toc = false
  description = "チラシの裏側に書き殴った雑な技術ブログ"
