baseurl = "https://www.kofuk.org/"
title = "kofuk's blog"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
paginate = "10"
theme = "Mainroad"
hasCJKLanguage = true
summaryLength = 300
disqusShortname = ""
googleAnalytics = ""
newContentEditor = "emacs"
enableEmoji = true

[Author]
  name = "Koki Fukuda"
  bio = "GNU/Linux, Bash, C++, Emacs が好きな地球人。完全理解者に早くなりたい。"
  avatar = "https://www.gravatar.com/avatar/621e74aa419b530d81adb56ddc16db12?s=0"

[Params]
  subtitle = "チラシの裏もどき"
  description = "主に技術的な情報を自分用のメモを兼ねて書いています。"
  copyright = "Koki Fukuda"
  opengraph = true
  twitter_cards = true
  readmore = true
  authorbox = true
  toc = false
  pager = true
  post_meta = ["date", "categories", "translations"]
  mainSections = "blog"
  dateformat = "2006-01-02"
  mathjax = true
  highlightColor = "#0032a8"

[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "recent", "categories", "taglist", "social", "languages"]

[Params.widgets]
  recent_num = 5
  tags_counter = true

[Params.widgets.social]
  facebook = ""
  twitter = "man_2_fork"
  instagram = ""
  linkedin = ""
  telegram = ""
  github = "kofuk"
  gitlab = "KoFuk"
  bitbucket = ""
  email = "ko.fu.dev+blog {a} gmail.com"

[[Params.widgets.social.custom]]
  title = "View Source Repository"
  url = "https://github.com/kofuk/www.kofuk.org"
  icon = "svg/repo.svg"
