name: deploy
on:
  push:
    branches:
      - 'master'

env:
  HUGO_VERSION: '0.108.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: ${{ env.HUGO_VERSION }}
          extended: true
      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: /tmp/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ env.HUGO_VERSION }}
          restore-keys: |
            ${{ runner.os }}-hugomod-
      - name: Configure Build
        run: |
          mkdir -p layouts/_default
          cp etc/list.bonsai.json layouts/_default/.
          cat etc/gen-bonsai-json.config.snippet >>config.toml
      - name: Build
        run: hugo    # we don't like minification.
      - name: Update Elasticsearch Index
        env:
          ELASTICSEARCH_URL: ${{ secrets.ELASTICSEARCH_URL }}
        run: |
          curl -X PUT "${ELASTICSEARCH_URL}/_bulk?refresh" -H 'Content-Type: application/x-ndjson' --data-binary '@public/bonsai.json'
